DoHaveCourse(StudentId, StudentName, GroupId) :-
    Students(StudentId, StudentName, GroupId),
    Groups(GroupId, GroupName),
    Plan(GroupId, :CourseId, LecturerId).
DoHaveMark(StudentId) :-
    Students(StudentId, StudentName, GroupId),
    Marks(StudentId, :CourseId, Mark).
Result(StudentId, StudentName, GroupName) :-
    DoHaveCourse(StudentId, StudentName, GroupId),
    Groups(GroupId, GroupName),
    not DoHaveMark(StudentId).